version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my-network

  frontend-http:
    build: ./frontend/docker-http-server
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend-app:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge